spring:
  application:
    name: hotel-booking-service
  datasource:
       url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
       driverClassName: org.h2.Driver
       username: sa
       password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
    ddl-auto: create
    show-sql: true
  h2:
    console:
      enabled: true
server:
     port: 8092
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  healthcheck:
        healthcheck:
           enabled: true
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
